### ISSUE TITLE
Add hint in documentation

### ISSUE THREAD

**Issue by atxbyea** [Jakeler/ble-serial#97]
Note: for general support questions, please use the discussions tab. This is the template for bugs in ble-serial.
Make sure you have completely read the [README](https://github.com/Jakeler/ble-serial/blob/master/README.md), searched through the [issues](https://github.com/Jakeler/ble-serial/issues?q=+) and [discussions](https://github.com/Jakeler/ble-serial/discussions).

**Describe the bug**
For any users who have bought an Airconsole BLE, I've been struggling for a while getting this to work in linux, however Airconsole support hasn't even bothered answering my emails.

`ble-serial` does not find the desired values for read and write, and the descriptions from the Airconsole are mostly "Unknown", also it goes to sleep quite quickly

To get an Airconsole BLE to work (great product with immense battery life by the way)

- First do a `ble-scan` it will now wake up
- Secondly do a `ble-scan -d <MAC> and list the values (I'm not sure if the UUIDs are the same on all)
- Look at the output, there are multiple SERVICE handles, almost all are "Unknown"
- For me the correct one was the same for read and write, and was the one called "Handle: 10"

example

```
SERVICE 0f1e4b13-16d2-4396-bf25-000000000000 (Handle: 9): Unknown
     CHARACTERISTIC 0f1e4b13-16d2-4396-bf25-000000000001 (Handle: 10): Unknown ['write-without-response', 'write', 'notify']
```

thanks for making a great software!

**Comment by Jakeler** [comment]
Hey, thanks for sharing the infos for this device! 
So you got it working with the instructions using deep scan and found the correct uuid. Idk is there anything specific that could be improved in the existing docu/readme? 

We could maybe add it to the autodetect list, but I like to have a specification from the manufacturer, employee or at least multiple users confirming the same uuid.

Otherwise this issue can be closed, others can still find it by searching for Airconsole BLE etc.

**Comment by atxbyea** [comment]
Ah, sorry, would be my assumption that since the Airconsole BLE device is the only one with serial port I've seen it would be a common device in the userbase of this repository.

Just keeping it as a closed issue would also make it searchable, which is great, if any other users can confirm their UUIDs that would make it easy to implement in the code I guess.
