### ISSUE TITLE
Connection failed: Device not found

### ISSUE THREAD

**Issue by pH-Valiu** [Jakeler/ble-serial#99]
I get the error: "Bluetooth connection failed. Device not found", although the device clearly exists as I managed to do ble-scan where it popped up and even managed to do a deep scan on it. 
(The name  of the device is "Not Set")

Can anyone help me?
![grafik](https://github.com/Jakeler/ble-serial/assets/110403905/1a8d1a39-a2d1-412d-8df6-c3a8b3c0b2a0)

**Comment by Jakeler** [comment]
Try with `--address-type random`

**Comment by Jakeler** [comment]
The process to establish a connection can be different, depending on the type it first has to cryptographically derive the actual address. See: https://novelbits.io/bluetooth-address-privacy-ble/
In your case it's the random static type (0xFF is ..11). 

I could probably make this parameter optional though, because the ble stack already knows which one it is when it detects the device/advertisement.

**Comment by pH-Valiu** [comment]
Thank you for the answer
